project:
  type: website
  output-dir: docs
  
website:
  title: "Luma Lazarini"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: github
        href: https://github.com/lumalazarini
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Luma Lazarini"

format:
  html:
    theme: minty
    toc: true

editor: source

